/*
* Criar um indice na tabela na coluna Login.
*/

IF EXISTS(SELECT Name FROM sysindexes WHERE Name = 'IDX_USUARIO_LOGIN')
	BEGIN
		DROP INDEX IDX_USUARIO_LOGIN ON USUARIO
	END

CREATE UNIQUE INDEX IDX_USUARIO_LOGIN ON USUARIO (LOGIN);